### ISSUE TITLE
Not In GW2-UOAOM (Add-on Manager)

### ISSUE THREAD

**Issue by Void2258** [Friendly0Fire/GW2Clarity#12]
There is no option to install GW2clarity in the add-on manager, despite this being mentioned as an install option. GW2Radial is there, but not clarity. Or it's named differently in the manager.

**Comment by Friendly0Fire** [comment]
The addon *loader* can be installed with the manager, but Clarity is currently in pre-alpha and intentionally not available in the manager until it's in beta (at minimum).
