### ISSUE TITLE
No Gw2 Launch when add with LaunchBuddy

### ISSUE THREAD

**Issue by zanagraf** [Friendly0Fire/GW2Clarity#16]
**Describe the bug**
I try to add Clarity to a GW2 launchbuddy (i add the clarity dll to it launch), but it block the launch completly

**To Reproduce**
1. Do 'Add Dll to a GW2 Launchbuddy account'
2. Then do 'Launch GW2'
3. Launch full block

**Expected behavior**
Can work with launch buddy (i only need this wonderfull on my main account)

**Screenshots**
no scree,

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: RX580
 - Chainloading, any

**Additional context**
TY !

**Comment by Friendly0Fire** [comment]
Sorry, I have only heard negative things about LaunchBuddy interfering with addons, so I can't really recommend using it. This is unfortunately not something in my control.

I would recommend GW2Launcher instead.

**Comment by zanagraf** [comment]
thanks a lot.

GW2launcher is nice i know but isn't compatible with my old rig (they don't launch GW2 in the same way)

**Comment by Friendly0Fire** [comment]
Well that's unfortunate... My only suggestion would be to complain to the LaunchBuddy dev. They haven't worked with addon developers at all as far as I'm aware and it really would be time to change that.
