### ISSUE TITLE
KERNELBASE.dll Warning and dump file

### ISSUE THREAD

**Issue by ehernandezll** [Friendly0Fire/GW2Clarity#19]
Starting Gw2 with Clarity throws the following warning in "gw2clarity.log" and creates a dump file for each logging. Addon works just fine.

[11:12:38.5338499|WRN] Intercepted exception in module 'C:\WINDOWS\System32\KERNELBASE.dll', address 0x7ffc0423cd29, code 0xe06d7363.

How can I solve the issue or stop creating dump files?

**Comment by Kiipey** [comment]
desactivate in settings graphics "dx9"

**Comment by Friendly0Fire** [comment]
Without further activity I'll be closing this now. Feel free to reopen with more details if the issue persists.
