### ISSUE TITLE
Showing all the boons even though i have no boons.

### ISSUE THREAD

**Issue by lightningdt** [Friendly0Fire/GW2Clarity#21]
I have checked the box for it to show only during combat. Once I get in combat, all the boons in the grid is showing up even though I don't have any boons. I don't think it is reading what boons I have.

**Comment by Zyian** [comment]
Check your configuration, you need to make sure that at 0 stacks it is set to Alpha 0 (Transparent) while at anything above 0 will show the icon

**Comment by knoxfighter** [comment]
The default settings currently do not show boons if you have you have them. You can take my options as a starting point.
Replace the existing file in `<GW2>/addons/gw2clarity`.
(Extract the zip into that folder, i am not allowed to upload json files directly)
[config.zip](https://github.com/Friendly0Fire/GW2Clarity/files/10495009/config.zip)
