### ISSUE TITLE
Stack detection stopped working on Feb. 28 patch

### ISSUE THREAD

**Issue by AstanVizu** [Friendly0Fire/GW2Clarity#27]
The detection of stacks for buffs and conditions stopped working since the Feb. 28 patch of GW2.
In more detail, setting a different color/opacity for 0 stacks and for 1-25 stacks will result in always showing the color/opacity for 0 stacks and never switch to the one for 1-25 stacks, even when applying the boon or condition.

Please let me know in case you need any files.

Thanks!

**Comment by Friendly0Fire** [comment]
Fixed in 0.0.17!
