### ISSUE TITLE
Fatal error while iterating through buff table

### ISSUE THREAD

**Issue by unrelentingsarcasm** [Friendly0Fire/GW2Clarity#44]
**Describe the bug**
Fatal error while iterating through buff table

**To Reproduce**
I get a notification window for the error every time I start up the game with GW2Clarity.  This issue started after the SOTO release and subsequent GW2Clarity update through the Addon Manager.

**Expected behavior**
That there wouldn't be a fatal error while iterating through buff table.

**Screenshots**
![image](https://github.com/Friendly0Fire/GW2Clarity/assets/69797676/f4cc20ff-8a1a-4acf-af99-618fc22f6c2c)

**System configuration (please fill in):**
 - OS: Windows 10
 - GPU: nVidia RTX2080
 - Chainloading, if any: UOAOM loads Arc, GW2 Radial, GW2Clarity, GShade

**Comment by Friendly0Fire** [comment]
Did you update to the latest version?

**Comment by knoxfighter** [comment]
Clarity is not available in the Addon Manager. You have to update  manually. Do so and the error will go away.

**Comment by unrelentingsarcasm** [comment]
That worked.  Thanks.
