### ISSUE TITLE
Crashes on second "/wiki" command

### ISSUE THREAD

**Issue by klearscreen** [Friendly0Fire/GW2Clarity#50]
**Describe the bug**
The game crashes after 2 uses of the "/wiki" command.

**To Reproduce**
1. Run the  "/wiki" command twice with any argument.
2. The game crashes and doesn't process the second wiki request.

**Expected behavior**
I would expect the game not to crash and open the correct wiki page.

**System configuration (please fill in):**
 - OS: Windows 11
 - GPU: NVIDIA RTX 3060 
 - Chainloading: BlishHUD -> Arcdps BlishHUD Integration -> arcdps -> GW2Clarity

**Additional context**
I am using the updated [getbuffs.dll](https://github.com/Friendly0Fire/GW2Clarity/commit/df34a5538c671f887c2ad495ab8be1a498cc3fd0).

**Comment by Friendly0Fire** [comment]
Do you have that issue without Clarity? Without any addon?

**Comment by klearscreen** [comment]
It doesn't happen when I remove Clarity.

**Comment by klearscreen** [comment]
Actually, it doesn't crash if I remove any of BlishHUD, arcdps or GW2Clarity.
It only crashes if the 3 are running.

**Comment by Friendly0Fire** [comment]
That tracks with what I've been able to gather from other devs. Looks like it's a problem with certain configurations with no clear cause, so we're just waiting for a fix. I'm afraid there's nothing I can do.
